-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 23:42:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apigovernance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `api_capabilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_capabilities` ;

CREATE TABLE IF NOT EXISTS `api_capabilities` (
  `API_CAPABILITIES_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `API_CAPABILITY_NAME` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`API_CAPABILITIES_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `api_resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_resources` ;

CREATE TABLE IF NOT EXISTS `api_resources` (
  `API_RESOURCES_ID` INT(11) NOT NULL,
  `API_RESOURCE_NAME` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`API_RESOURCES_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `api_capabilities_resources_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_capabilities_resources_mapping` ;

CREATE TABLE IF NOT EXISTS `api_capabilities_resources_mapping` (
  `API_CAPABILITIES_MAPPING_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `API_CAPABILITIES_ID` INT(11) NULL DEFAULT NULL,
  `API_RESOURCES_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`API_CAPABILITIES_MAPPING_ID`),
  CONSTRAINT `API_CAPABILITIES_RESMAPPING`
    FOREIGN KEY (`API_CAPABILITIES_ID`)
    REFERENCES `api_capabilities` (`API_CAPABILITIES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `API_RESOURCES_CAPRESMAPPING`
    FOREIGN KEY (`API_RESOURCES_ID`)
    REFERENCES `api_resources` (`API_RESOURCES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `API_CAPABILITIES_RESMAPPING_idx` ON `api_capabilities_resources_mapping` (`API_CAPABILITIES_ID` ASC);

CREATE INDEX `API_RESOURCES_CAPRESMAPPING_idx` ON `api_capabilities_resources_mapping` (`API_RESOURCES_ID` ASC);


-- -----------------------------------------------------
-- Table `api_main`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_main` ;

CREATE TABLE IF NOT EXISTS `api_main` (
  `API_MAIN_ID` INT(11) NOT NULL,
  `API_NAME` VARCHAR(200) NULL DEFAULT NULL,
  `JIRA_TICKET` VARCHAR(250) NULL DEFAULT NULL,
  `IS_EXTERNAL` CHAR(1) NULL DEFAULT NULL,
  `IS_NEW` CHAR(1) NULL DEFAULT NULL,
  `API_TYPE` VARCHAR(45) NULL DEFAULT NULL,
  `CREATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME NULL DEFAULT NULL,
  `UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  `UPDATED_DATE` DATETIME NULL DEFAULT NULL,
  `TARGET_DATE` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`API_MAIN_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Api requests';

CREATE UNIQUE INDEX `JIRATicket_UNIQUE` ON `api_main` (`JIRA_TICKET` ASC);


-- -----------------------------------------------------
-- Table `api_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_info` ;

CREATE TABLE IF NOT EXISTS `api_info` (
  `Id` INT(11) NOT NULL,
  `api_main_id` INT(11) NULL DEFAULT NULL,
  `API_DEPENDENCIES` VARCHAR(150) NULL DEFAULT NULL,
  `INTENTED_FOR_INTERNAL_UI` CHAR(1) NULL DEFAULT NULL,
  `DATA_SOURCES` VARCHAR(200) NULL DEFAULT NULL,
  `ENTITLEMENT_SERVICES` VARCHAR(200) NULL DEFAULT NULL,
  `VALUE_PROPOSITION` VARCHAR(500) NULL DEFAULT NULL,
  `CLIENT_SEGMENTS` VARCHAR(45) NULL DEFAULT NULL,
  `BUSINESS_CAPABILITIES` VARCHAR(45) NULL DEFAULT NULL,
  `REVENUE_MODEL` VARCHAR(300) NULL DEFAULT NULL,
  `REVENUE_GENERATION` DECIMAL(8,2) NULL DEFAULT NULL,
  `ESTIMATED_COST_TO_BUILD` DECIMAL(8,2) NULL DEFAULT NULL,
  `SAVINGS` DECIMAL(8,2) NULL DEFAULT NULL,
  `LEVEL_OF_EFFORT` INT(11) NULL DEFAULT NULL,
  `DURATION` INT(11) NULL DEFAULT NULL,
  `AVG_NUMBER_OF_CALLS` INT(11) NULL DEFAULT NULL,
  `SLA` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_apiinfo_main`
    FOREIGN KEY (`api_main_id`)
    REFERENCES `api_main` (`API_MAIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_apiinfo_main_idx` ON `api_info` (`api_main_id` ASC);


-- -----------------------------------------------------
-- Table `api_operations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_operations` ;

CREATE TABLE IF NOT EXISTS `api_operations` (
  `API_OPERATIONS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `API_OPERATION_NAME` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`API_OPERATIONS_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `api_resources_main_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_resources_main_mapping` ;

CREATE TABLE IF NOT EXISTS `api_resources_main_mapping` (
  `API_RESOURCES_MAPPING_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `API_MAIN_ID` INT(11) NULL DEFAULT NULL,
  `API_RESOURCES_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`API_RESOURCES_MAPPING_ID`),
  CONSTRAINT `API_MAIN_RESOURCES_MAPPING`
    FOREIGN KEY (`API_MAIN_ID`)
    REFERENCES `api_main` (`API_MAIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AP_RESOURCES_RESOURCEMAPPING`
    FOREIGN KEY (`API_RESOURCES_ID`)
    REFERENCES `api_resources` (`API_RESOURCES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `API_RESOURCES_idx` ON `api_resources_main_mapping` (`API_MAIN_ID` ASC);

CREATE INDEX `AP_RESOURCES_RESOURCEMAPPING_idx` ON `api_resources_main_mapping` (`API_RESOURCES_ID` ASC);


-- -----------------------------------------------------
-- Table `api_tracker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_tracker` ;

CREATE TABLE IF NOT EXISTS `api_tracker` (
  `API_TRACKER_ID` INT(11) NOT NULL,
  `API_MAIN_ID` INT(11) NULL DEFAULT NULL,
  `TODAY_DATE` DATETIME NULL DEFAULT NULL,
  `NARB_REVIEW_DATE` DATETIME NULL DEFAULT NULL,
  `NOTIFIED_IN_JIRA` CHAR(1) NULL DEFAULT NULL,
  `ADDED_TO_INVITE` CHAR(1) NULL DEFAULT NULL,
  `REVIEWED` CHAR(1) NULL DEFAULT NULL,
  `API_STATUS` INT(11) NULL DEFAULT NULL,
  `REFACTOR_DATE` DATETIME NULL DEFAULT NULL,
  `NOTES` VARCHAR(1500) NULL DEFAULT NULL,
  `BUSINESS_UNIT` VARCHAR(200) NULL DEFAULT NULL,
  `BUSINESS_PROD_OWNER` VARCHAR(200) NULL DEFAULT NULL,
  `REQUESTER` VARCHAR(200) NULL DEFAULT NULL,
  `PROJECT_MANAGER` VARCHAR(200) NULL DEFAULT NULL,
  `TECHNICAL_LEAD` VARCHAR(200) NULL DEFAULT NULL,
  `DCA` VARCHAR(200) NULL DEFAULT NULL,
  `BUSINESS_ANALYST` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`API_TRACKER_ID`),
  CONSTRAINT `API_MAIN_TRACKER_MAPPING`
    FOREIGN KEY (`API_MAIN_ID`)
    REFERENCES `api_main` (`API_MAIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `API_MAIN_TRACKER_MAPPING_idx` ON `api_tracker` (`API_MAIN_ID` ASC);


-- -----------------------------------------------------
-- Table `api_operations_resources_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_operations_resources_mapping` ;

CREATE TABLE IF NOT EXISTS `api_operations_resources_mapping` (
  `API_OPERATIONS_MAPPING_ID` INT(11) NOT NULL,
  `API_OPERATIONS_ID` INT(11) NULL,
  `API_RESOURCES_ID` INT(11) NULL,
  PRIMARY KEY (`API_OPERATIONS_MAPPING_ID`),
  CONSTRAINT `fk_api_operations_resources_mapping_api_operations1`
    FOREIGN KEY (`API_OPERATIONS_ID`)
    REFERENCES `api_operations` (`API_OPERATIONS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_api_operations_resources_mapping_api_resources1`
    FOREIGN KEY (`API_RESOURCES_ID`)
    REFERENCES `api_resources` (`API_RESOURCES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_api_operations_resources_mapping_api_operations1_idx` ON `api_operations_resources_mapping` (`API_OPERATIONS_ID` ASC);

CREATE INDEX `fk_api_operations_resources_mapping_api_resources1_idx` ON `api_operations_resources_mapping` (`API_RESOURCES_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
